# Docker Compose with enhanced security using Docker secrets
# Usage: docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up -d
version: '3.8'

secrets:
  google_client_id:
    external: true
    name: setliststudio_google_client_id
  google_client_secret:
    external: true
    name: setliststudio_google_client_secret
  microsoft_client_id:
    external: true
    name: setliststudio_microsoft_client_id
  microsoft_client_secret:
    external: true
    name: setliststudio_microsoft_client_secret
  facebook_app_id:
    external: true
    name: setliststudio_facebook_app_id
  facebook_app_secret:
    external: true
    name: setliststudio_facebook_app_secret

services:
  setliststudio-web:
    secrets:
      - google_client_id
      - google_client_secret
      - microsoft_client_id
      - microsoft_client_secret
      - facebook_app_id
      - facebook_app_secret
    environment:
      # Remove OAuth secrets from environment variables
      # These will be read from mounted secret files instead
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/setliststudio.db
      # OAuth secrets are now loaded from Docker secrets files
      - USE_DOCKER_SECRETS=true