version: '3.8'

services:
  setliststudio-web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/setliststudio.db
      - Authentication__Google__ClientId=${GOOGLE_CLIENT_ID:-}
      - Authentication__Google__ClientSecret=${GOOGLE_CLIENT_SECRET:-}
      - Authentication__Microsoft__ClientId=${MICROSOFT_CLIENT_ID:-}
      - Authentication__Microsoft__ClientSecret=${MICROSOFT_CLIENT_SECRET:-}
      - Authentication__Facebook__AppId=${FACEBOOK_APP_ID:-}
      - Authentication__Facebook__AppSecret=${FACEBOOK_APP_SECRET:-}
    volumes:
      - setliststudio-data:/app/data
      - setliststudio-logs:/app/logs
      # Security: Mount temporary directories
      - /tmp:/tmp:rw,nosuid,nodev,noexec
    tmpfs:
      - /app/temp:rw,nosuid,nodev,noexec,size=100m
    restart: unless-stopped
    # Security: Resource limits
    mem_limit: 512m
    memswap_limit: 512m
    cpu_quota: 50000  # 0.5 CPU
    pids_limit: 100
    # Security: Drop capabilities and run read-only
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    security_opt:
      - no-new-privileges:true
      - apparmor:docker-default
    # User namespace remapping (requires daemon configuration)
    user: "1001:1001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  setliststudio-data:
  setliststudio-logs: