# Kubernetes Deployment Configuration for Setlist Studio
# Provides auto-scaling based on CPU/Memory with load balancing

apiVersion: apps/v1
kind: Deployment
metadata:
  name: setlist-studio-web
  namespace: setlist-studio
  labels:
    app: setlist-studio-web
    version: "1.0.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: setlist-studio-web
  template:
    metadata:
      labels:
        app: setlist-studio-web
        version: "1.0.0"
    spec:
      containers:
      - name: setlist-studio-web
        image: setlist-studio:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: LoadBalancing__IsLoadBalanced
          value: "true"
        - name: LoadBalancing__InstanceId
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LoadBalancing__InstanceName
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: setlist-studio-secrets
              key: database-connection
        - name: Database__Provider
          value: "PostgreSQL"
        - name: Database__MaxPoolSize
          value: "50"
        - name: Database__MinPoolSize
          value: "5"
        - name: ConnectionStrings__Redis
          valueFrom:
            secretKeyRef:
              name: setlist-studio-secrets
              key: redis-connection
        - name: Authentication__Google__ClientId
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: google-client-id
        - name: Authentication__Google__ClientSecret
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: google-client-secret
        - name: Authentication__Microsoft__ClientId
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: microsoft-client-id
        - name: Authentication__Microsoft__ClientSecret
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: microsoft-client-secret
        - name: Authentication__Facebook__AppId
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: facebook-app-id
        - name: Authentication__Facebook__AppSecret
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: facebook-app-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health/ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health/simple
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: app-data
          mountPath: /app/data
        - name: app-logs
          mountPath: /app/logs
        - name: tmp
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: setlist-studio-data-pvc
      - name: app-logs
        emptyDir:
          sizeLimit: 1Gi
      - name: tmp
        emptyDir:
          sizeLimit: 100Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: setlist-studio-web-service
  namespace: setlist-studio
  labels:
    app: setlist-studio-web
spec:
  selector:
    app: setlist-studio-web
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: setlist-studio-web-hpa
  namespace: setlist-studio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: setlist-studio-web
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: setlist-studio-web-pdb
  namespace: setlist-studio
spec:
  selector:
    matchLabels:
      app: setlist-studio-web
  minAvailable: 2